
        <div id="pop-login">
            <div id="head-pop-login">
                    <div id="head-pop-login-inner">
                        <div id="head-pop-login-inner-left">ClubNeu</div>
                    </div>
            </div>
            <div id="body-pop-login">
                <div class="encabezado-caja-restablecer">
                    <div class="form-caja-restablecer">
                        <span><?php echo $this->translate('usuario.login.form.restsblecer.titulo');?></span>
                        <p><?php echo $this->translate('usuario.login.form.restablecer.text');?></p>    
                        <?php echo $this->form_restablecer?>
                    </div>
                </div>
                
            </div>
        </div>        
   