
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html style="margin-top: 0px !important; padding-top: 0px !important; width: 100%">
<head>
	<style type="text/css">
		html, body{ width:100%; margin-top: 0px !important; padding-top: 0px !important; }
		body{ background-color:#FFFFFF; margin-top: 0px !important; padding-top: 0px !important; font-family:sans-serif; }
		table{ margin-top: 0px !important; padding-top: 0px !important; }
		body{ padding-top:0; padding-right:0; padding-bottom:0; padding-left:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0; color:#000000 !important; font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size:13px; line-height:17px; }
		h1, .faux_h1{ padding-top:0; padding-right:0; padding-bottom:0; padding-left:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0; color:#000000 !important; font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size:20px; line-height:26px; }
		.faux_h1_color_color{ color:#000000; }
		h2, .faux_h2{ padding-top:0; padding-right:0; padding-bottom:0; padding-left:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0; color:#000000 !important; font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size:18px; line-height:26px; }
		.faux_h2_color_color{ color:#000000; }
		h3 { padding-top:0; padding-right:0; padding-bottom:0; padding-left:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0; color:#000000 !important; font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size:15px; line-height:26px; }
		p, .faux_p{ padding-top:0; padding-right:0; padding-bottom:0; padding-left:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0; color:#000000 !important; font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size:13px; line-height:17px; }
		.faux_p_color_color{ color:#000000; }
		a, .faux_a{ text-decoration:underline; padding-top:0; padding-right:0; padding-bottom:0; padding-left:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0; color:#000000 !important; font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size:13px; line-height:17px; }
		.faux_a_color_color{ color:#1122CC; }
		.wysiwyg-text-align-right{ text-align: right; }
		.wysiwyg-text-align-center { text-align: center; }
		.wysiwyg-text-align-left{ text-align: left; }
		.wysiwyg-text-align-justify{ text-align: justify; }
	</style>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body style="background-color: #FFFFFF; color: #000000 !important; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 13px; line-height: 17px; margin-bottom: 0; margin-left: 0px; margin-right: 0; margin-top: 0px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0px; width: 100%" bgcolor="#FFFFFF">
	<table width="100%" cellspacing="0" cellpadding="0" align="center" style="background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" bgcolor="#DDDDDD">
		<tbody>
			<tr align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
				<td valign="top" align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
					<table width="650" cellspacing="0" cellpadding="0" border="0" align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
						<tbody>
							<tr align="left" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
								<td width="650">
									<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-top: 0px !important; padding-top: 0px !important">
										<tbody>
											<tr align="left" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
												<td width="650">
													<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-top: 0px !important; padding-top: 0px !important">
														<tbody>
															<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0px; border-top-width: 0; height: 20px">
																<td width="650" valign="top" height="20" align="left" style="background-color: #FFFFFF" bgcolor="#FFFFFF"></td>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
	<table align="center" cellpadding="0" cellspacing="0" width="100%" style="background-color: #FFFFFF; border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-bottom: 0; margin-left: 0; margin-right: 0; margin-top: 0px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0px" bgcolor="#DDDDDD">
		<tr align="center" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
			<td align="center" valign="top" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
				<table width="650" align="center" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-bottom: 0; margin-left: 0; margin-right: 0; margin-top: 0px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0px">
					<tbody>
						<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
							<td width="650">
								<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
									<tbody>
										<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
											<td width="32" height="55" align="left" valign="top" style="">
												<img height="55" src="http://e-fbk.com/mailneu/head-left.jpg" style="border-bottom-width: 0; border-left-width: 0; border-right-width: 0; border-top-width: 0; display: block; line-height: 1; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0" width="32">
											</td>
											<td width="586" height="55" align="left" valign="top" style="">
												<img height="55" src="http://e-fbk.com/mailneu/head-mid.jpg" style="border-bottom-width: 0; border-left-width: 0; border-right-width: 0; border-top-width: 0; display: block; line-height: 1; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0" width="586">
											</td>
											<td width="32" height="55" align="left" valign="top" style="">								
												<img height="55" src="http://e-fbk.com/mailneu/head-right.jpg" style="border-bottom-width: 0; border-left-width: 0; border-right-width: 0; border-top-width: 0; display: block; line-height: 1; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0" width="32">
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
							<td width="650">
								<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
									<tbody>
										<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
											<td width="32" align="left" valign="top" bgcolor="#DDDDDD" style="">
											</td>
											<td width="586" align="left" valign="top">
												<table width="586" align="center" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-bottom: 0; margin-left: 0; margin-right: 0; margin-top: 0px; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0px">
													<tbody>
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="586" height="31" align="left" valign="top" style="">
																				<img height="31" src="http://e-fbk.com/mailneu/entradas-mid.jpg" style="border-bottom-width: 0; border-left-width: 0; border-right-width: 0; border-top-width: 0; display: block; line-height: 1; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0" width="586">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="30" height="105" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																			<td width="263" height="105" align="left" valign="top" bgcolor="#ffffff">
																				<!-- TEXTO - CABECERA -->
																			</td>
																			<td width="293" height="105" align="left" valign="top" style="">
																				<img height="105" src="http://e-fbk.com/mailneu/entradas-bot.jpg" style="border-bottom-width: 0; border-left-width: 0; border-right-width: 0; border-top-width: 0; display: block; line-height: 1; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0" width="293">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<!-- INFO ENTRADAS-->
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="30" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																			<td width="525" align="left" valign="top" bgcolor="#FFFFFF" style="">
																				<p>Hola <?php echo $this->user_data['nombre']?>, tu amigo <b><?php echo $this->user_data['nombre_amigo']?></b> se ha enrollado y te ha enviado esta entrada para ir a ver un espectáculo!</p>
																			</td>
																			<td width="31" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<!-- END INFO ENTRADAS -->														
														<!-- SESION SEPARADOR -->
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="586" height="20" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<!-- END - SESION SEPARADOR -->
														<!-- INFO ENTRADAS-->
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="30" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																			<td width="525" align="left" valign="top" bgcolor="#FFFFFF" style="">
																				<p>Imprime esta entrada y ven al teatro a disfrutar de esta obra.</p>
																			</td>
																			<td width="31" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<!-- END INFO ENTRADAS -->														
														<!-- SESION SEPARADOR -->
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="586" height="20" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<!-- END - SESION SEPARADOR -->
														<!-- SESION BLOQUE -->
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="30" bgcolor="#FFFFFF" align="left" valign="top" style=""></td>
																			<!-- ZONA IMAGEN CARTEL -->
																			<td width="151" align="left" valign="top" bgcolor="#DDDDDD" style="">
																				<img src="http://e-fbk.com/mailneu/cartel-01.jpg" style="border-bottom-width: 0; border-left-width: 0; border-right-width: 0; border-top-width: 0; display: block; line-height: 1; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0" width="151">
																			</td>
																			<!-- ZONA IMAGEN CARTEL -->
																			<!-- ZONA CONTENIDO -->
																			<td width="374" align="left" valign="top" bgcolor="#DDDDDD" style="">
																				<table width="374" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																					<tbody>
																						<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																							<td width="20" align="left" valign="top" style=""></td>
																							<td width="334" align="left" valign="top" bgcolor="#DDDDDD" style="">
																								<!--dfdsfds-->
																								<table width="334" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																									<tbody>
																										<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																											<td width="334" height="10" align="left" valign="top" bgcolor="#DDDDDD" style=""></td>
																										</tr>
																										<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																											<td width="334" align="left" valign="top" bgcolor="#DDDDDD" style="">
																												<h3>Berto Romero 2013</h3>
																												<p>Sábado 4 de Febrero de 2013 20:30h</p>
																												<p>Sala Xavier Fábregas</p>
																											</td>
																										</tr>
																										<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																											<td width="334" height="10" align="left" valign="top" bgcolor="#DDDDDD" style=""></td>
																										</tr>
																										<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																											<td width="334" align="left" valign="top" bgcolor="#DDDDDD" style="">
																												<!-- BUTACA -->
																												<table width="334" cellspacing="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																													<tbody>
																														<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																															<td align="left" valign="top" bgcolor="#DDDDDD">
																																<img width="115" height="115" src="http://e-fbk.com/mailneu/qr-sample.jpg" style="border: solid 1px #A4A4A4; display: block; line-height: 1; padding-bottom: 0; padding-left: 0; padding-right: 0; padding-top: 0">
																															</td>
																															<td width="2" height="15" align="left" bgcolor="#DDDDDD"></td>
																															<td width="208" height="15" align="left" valign="top">
																																<table width="206" cellspacing="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																																	<tbody>
																																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																																			<td height="15" align="left" valign="top" bgcolor="#FFFFFF" style="border: solid 1px #A4A4A4;" >
																																				<p style="margin-left:5px;">Fila 7 - Butaca 10</p>
																																			</td>
																																		</tr>
																																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																																			<td height="5" align="left" valign="top" bgcolor="#DDDDDD"></td>
																																		</tr>
																																	</tbody>
																																</table>
																															</td>
																														</tr>
																														<tr width="243" height="5" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0"></tr>
																													</tbody>
																												</table>
																												<!-- END BUTACA -->
																												
																											</td>
																										</tr>
																										
																										
																										<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																											<td width="334" height="10" align="left" valign="top" bgcolor="#DDDDDD" style=""></td>
																										</tr>
																									</tbody>
																								</table>
																							</td>										
																							<td width="20" align="left" valign="top" style=""></td>
																						</tr>
																					</tbody>
																				</table>
																			</td>
																			<!-- END ZONA CONTENIDO -->
																			<td width="31" bgcolor="#FFFFFF" align="left" valign="top" style="">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<tr align="left" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
															<td width="586">
																<table width="586" cellspacing="0" cellpadding="0" border="0" style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0; margin-top: 0px !important; padding-top: 0px !important">
																	<tbody>
																		<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0; border-top-width: 0">
																			<td width="586" height="20" align="left" valign="top" bgcolor="#FFFFFF" style="">
																			</td>
																		</tr>
																	</tbody>
																</table>
															</td>
														</tr>
														<!-- END - SESION BLOQUE -->
													</tbody>
												</table>
											</td>
											<td width="32" align="left" valign="top" bgcolor="#DDDDDD" style="">
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</table>
	<table width="100%" cellspacing="0" cellpadding="0" align="center" style="background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" bgcolor="#DDDDDD">
		<tbody>
			<tr align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
				<td valign="top" align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
					<table width="650" cellspacing="0" cellpadding="0" border="0" align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
						<tbody>
							<tr align="left" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
								<td width="650">
									<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-top: 0px !important; padding-top: 0px !important">
										<tbody>
											<tr align="left" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
												<td width="650">
													<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-top: 0px !important; padding-top: 0px !important">
														<tbody>
															<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0px; border-top-width: 0; height: 20px">
																<td width="650" valign="top" height="20" align="left" style="background-color: #DDDDDD" bgcolor="#DDDDDD"></td>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
	<table width="100%" cellspacing="0" cellpadding="0" align="center" style="background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px" bgcolor="#DDDDDD">
		<tbody>
			<tr align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
				<td valign="top" align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
					<table width="650" cellspacing="0" cellpadding="0" border="0" align="center" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px">
						<tbody>
							<tr align="left" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
								<td width="650">
									<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-top: 0px !important; padding-top: 0px !important">
										<tbody>
											<tr align="left" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px">
												<td width="650">
													<table width="650" cellspacing="0" cellpadding="0" border="0" style="border-bottom-style: none; border-bottom-width: 0px; border-collapse: collapse; border-left-style: none; border-left-width: 0px; border-right-style: none; border-right-width: 0px; border-spacing: 0px; border-top-style: none; border-top-width: 0px; margin-top: 0px !important; padding-top: 0px !important">
														<tbody>
															<tr style="border-bottom-width: 0; border-collapse: collapse; border-left-width: 0; border-right-width: 0; border-spacing: 0px; border-top-width: 0; height: 20px">
																<td width="650" valign="top" height="20" align="left" style="background-color: #FFFFFF" bgcolor="#FFFFFF"></td>
															</tr>
														</tbody>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</body>
</html>