<?php 
    $ruta = Zend_Registry::get('ruta'); 
    $ruta_gui = $ruta['dominio'].$ruta['base'].$ruta['frontticketing']['gui'];
    $ruta_includes = $ruta['server'].$ruta['base'].$ruta['includes'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <link rel="icon" href="<?php echo $this->url(array(),null, true);?>favicon.ico" type="image/x-icon" />
        <title><?php if (isset ($this->metatag)) echo $this->metatag['title']?> - TeatreNeu</title>
        <meta name="keywords" content="<?php if (isset ($this->metatag)) echo $this->metatag['description']?>" />
        <meta name="description" content="<?php if (isset ($this->metatag)) echo $this->metatag['keywords']?>" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>TeatreNeu</title>
        <?php echo  $this->getHelper("Cargador")->cargaScripts($this->cargador_arr); ?>
        <?php echo  $this->getHelper("Cargador")->cargaStyles($this->cargador_arr); ?>
        
    </head>
<body>
    <div id="wrapper_top">	
        <div id="top_menu">
            <ul>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'index'), null, true)?>"            <?php if ($this->controlador=='index' && $this->accion=='index') echo 'class="active" '?>><?php echo $this->translate('menu.inicio');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'espectaculos'), null, true)?>"     <?php if ($this->controlador=='index' && $this->accion=='espectaculos') echo 'class="active" '?>><?php echo $this->translate('menu.espectaculos');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'actualidad'), null, true)?>"       <?php if ($this->controlador=='index' && $this->accion=='actualidad') echo 'class="active" '?>><?php echo $this->translate('menu.actualidad');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'club'), null, true)?>"             <?php if ($this->controlador=='index' && $this->accion=='club') echo 'class="active" '?>><?php echo $this->translate('menu.club');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'quienes-somos'), null, true)?>"    <?php if ($this->controlador=='index' && $this->accion=='quienes-somos') echo 'class="active" '?>><?php echo $this->translate('menu.quien');?></a> </li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'salas'), null, true)?>"            <?php if ($this->controlador=='index' && $this->accion=='salas') echo 'class="active" '?>><?php echo $this->translate('menu.salas');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'servicios'), null, true)?>"        <?php if ($this->controlador=='index' && $this->accion=='servicios') echo 'class="active" '?>><?php echo $this->translate('menu.servicios');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'prensa'), null, true)?>"           <?php if ($this->controlador=='index' && $this->accion=='prensa') echo 'class="active" '?>><?php echo $this->translate('menu.prensa');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'donde-estamos'), null, true)?>"    <?php if ($this->controlador=='index' && $this->accion=='donde-estamos') echo 'class="active" '?>><?php echo $this->translate('menu.donde');?></a></li>
                <li><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'contacto'), null, true)?>"         <?php if ($this->controlador=='index' && $this->accion=='contacto') echo 'class="active" '?>><?php echo $this->translate('menu.contacto');?></a></li>			
            </ul>
        </div>
    </div>
    <div id="wrapper_ribbon"><div id="blank_cover_ribbon"></div></div>
    <div class="wrapper">
        <div id="logo_neu"><a href="<?php echo $this->url(array('module' => 'frontTeatreneu', 'controller' => 'index', 'action' => 'index'), null, true)?>"></a></div>
        <?php echo $this->layout()->content; ?>
    </div>
    <div id="wrapper_bottom">    
        <div class="wrapper footer_links">
            <div class="column left "><h3>Sobre nosotros</h3>
            <ul>
                    <li><a href="#">TEATRE NEU</a></li>
                    <li><a href="#">ESPECTACLES</a></li>
                    <li><a href="#">ACTUALITAT</a></li>
                    <li><a href="#">CLUB TEATRE NEU</a></li>
                    <li><a href="#">QUI SOM?</a> </li>
                    <li><a href="#">LES NOSTRES SALES</a></li>
                    <li><a href="#">ON SOM?</a></li>
                    <li><a href="#">CONTACTE</a></li>			
            </ul>
            </div>
            <div class="left "><h3>Actualidad</h3><img src="<?php echo $ruta_gui; ?>/regalateatre.jpg">
                    <p>Aquestes Festes REGALA TEATRE! El millor dels Regals!<br /> 
                    Regala Humor! Tu regales les entrades i l´afortunat/da tria els <br />
                    espectacles, el dia i l´hora que hi vol anar i amb qui. Així de fàcil! </p>
            </div>
            <div class="half_column right "><h3>Links interesantes</h3>
            <ul>
                    <li><a href="#">TEATRE NEU</a></li>
                    <li><a href="#">ESPECTACLES</a></li>
                    <li><a href="#">ACTUALITAT</a></li>
                    <li><a href="#">CLUB TEATRE NEU</a></li>
                    <li><a href="#">QUI SOM?</a> </li>
                    <li><a href="#">LES NOSTRES SALES</a></li>
                    <li><a href="#">ON SOM?</a></li>
                    <li><a href="#">CONTACTE</a></li>			
            </ul>
            </div>
        </div>
    </div>
    <div id="layer-notificaciones" style="display:none;">
        <div id="layer-notificaciones-holder">
            <div id="layer-notificaciones-logo" class=""></div>
            <div id="layer-notificaciones-content">
                <table id="layer-notificaciones-content-table"><tbody><tr><td>
                    <span>Hola Xavi, ¿sabias que tienes disponibles grandes descuentos en tu area de usuario?, accede haciendo click en este <a href="#">enlace</a></span>
                </td></tr></tbody></table>
            </div>
            <div id="layer-notificaciones-close" onclick="hideNotificaciones();"></div>
        </div>
    </div>
    <?php include_once($ruta_includes."/analyticstracking.php") ?>
    <script>//showNotificaciones();</script>
</body>
</html>
