<?php 
    $ruta = Zend_Registry::get('ruta'); 
    $ruta_gui = $ruta['dominio'].$ruta['base'].$ruta['regalo']['gui'];
    $ruta_regalo = $ruta['dominio'].$ruta['base'].$ruta['imagenes']['galeria']['regalo'].'/uploads';
?>
<head>
    <link rel="icon" href="/ticketingrupneu/public/favicon.ico" type="image/x-icon" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Regala Teatro</title>
    <body>
        <style>
            @font-face {
                font-family: 'Brush Script Std';
                font-style: normal;
                font-weight: 400;
                src: local('Brush Script Std'), local('Brush Script Std'), url(<?php echo $ruta['dominio'].$ruta['base']?>/comunes/css/BrushScriptStd.woff) format('woff');
            }
            body{
                font-family: Arial;
                margin:0;
            }
            #tarjeta-regalo-back{
                width:850px;
                height:1356px;
            }
            
            #background-tarjeta-regalo{
                width:850px;
                height:1356px;
                position:absolute;
            }
            #tarjeta-regalo-content{
                position:absolute;
                width:850px;
                height:1356px;
            }
            
            #trc-head{
                width:690px;
                height:185px;
                margin-left:56px;
                float:left;
                padding-left:50px;
                padding-top:25px;
            }
          
            #trc-head span{
                float:left;
                margin-top:2px;
                font-weight: bold;
            }
            
            #trc-ticket{
                width:640px;
                height:235px;
                margin-left:56px;
                margin-top:32px;
                padding-top:52px;
                padding-left:50px;
                float:left;
            }
            #trc-ticket-producto{
                float:left;
                height: 235px;
                margin-left:20px;
            }
            
            #trc-ticket-producto img{
                height: 235px;
            }
            
            #trc-ticket-center{
                float:left;
                width:260px;
                margin-left:23px;
                margin-top:28px;
            }
            
            #trc-ticket-qr{
                float:left;
                margin-left:10px;
                margin-top:97px;
            }   
            
            #trc-ticket-qr img{
                width:95px;
                height:95px;
            }
            
            #localizador{
                width:260px;
                font-size: 12px;
                float:left;
                font-weight: bold;
            }
            
            #num_entradas{
                width:260px;
                font-size: 28px;
                float:left;
                font-weight: bold;
            }
            
            #nombre_producto{
                width:260px;
                font-size: 14px;
                float:left;
                font-weight: bold;
            }
            
            #nombre_receptor_box{
                width:238px;
                height:32px;
                margin-top:5px;
                padding-left:10px;
                padding-right:10px;
                padding-top:10px;
                padding-bottom:10px;
                font-size: 14px;
                font-weight: bold;                
                float:left;
            }
            
            #nombre_receptor_holder{
                display: table-cell;
                vertical-align: middle;  
                height:32px;
            }
            
            #nombre_receptor_box_text{
                
                margin:0;
            }
            #url_explicacion {
                float:left;
                font-size: 12px;
                margin-top:10px;
            }
            #url_link {
                float:left;
                font-size: 12px;
                font-weight: bold;
                width:410px;
                margin-top:10px;
            }
            #trc-front{
                float:left;
                width: 515px;
                margin-top:490px;
                margin-left:128px;
                height:168px;
                padding-left:24px;
                padding-right:60px;
                padding-top:20px;
            }
            
            #trc-front-image-box{
                float:left;
                width:168px;
                height:167px;
            }
            
            #trc-front-image-box img{
                width:168px;
                height:167px;
            }
            
            #trc-front-text-area{
                float:left;
                margin-left:20px;
                width:295px;
                margin-top:50px;
                margin-left:50px;
            }
            #trc-front-text-area span{
                float:left;
                width:285px;
                font-family:Brush Script Std;
                color:#626153;
                font-size:20px;
                
            }
            #pegatina{
                width:85px;
                height:71px;
                position:absolute;
                float:left;
                margin-top:-40px;
                margin-left:-32px;
            }
        </style>
        <div id="tarjeta-regalo-back">
            <img id="background-tarjeta-regalo" src="<?php echo $ruta_gui?>/back-tarjeta-regalo.jpg">
            <div id="tarjeta-regalo-content">
                <div id="trc-head">
                    <span style="width:188px;"><?php echo $this->translate('tarjeta.imprimible.imprime')?></span>
                    <span style="width:180px;"><?php echo $this->translate('tarjeta.imprimible.recorta')?></span>
                    <span style="width:200px;"><?php echo $this->translate('tarjeta.imprimible.pliega')?></span>
                </div>
                <div id="trc-ticket">
                    <div id="trc-ticket-producto">
                        <img src="<?php echo $ruta_gui?>/<?php echo $this->vista_arr['imagen_producto']?>" />
                    </div>
                    <div id="pegatina">
                        <img src="<?php echo $ruta_gui?>/mini-pegatina.png">
                    </div>
                    <div id="trc-ticket-center">
                        <span id="localizador">Localizador: <?php echo $this->vista_arr['localizador']?></span>
                        <span id="num_entradas"><?php echo $this->vista_arr['numero_entradas']?> <?php echo $this->translate('tarjeta.imprimible.entradas');?></span>
                        <span id="nombre_producto"><?php echo $this->translate('tarjeta.imprimible.valido');?> <?php echo $this->vista_arr['nombre_producto']?></span>
                        <div id="nombre_receptor_box">
                            <div id="nombre_receptor_holder">
                                <p id="nombre_receptor_box_text"><?php echo $this->vista_arr['nombre_receptor']?></p>
                            </div>
                        </div>
                        <span id="url_explicacion"><?php echo $this->translate('tarjeta.imprimible.text')?></span>
                        <span id="url_link"><?php echo $this->vista_arr['link_reservar_short']?></span>
                    </div>
                    <div id="trc-ticket-qr">
                        <img src="<?php echo $this->url(array('idioma' => $this->idioma, 'module' => 'default', 'controller' => 'ticketing-utils', 'action' =>'qr', 'ct' => urlencode($this->vista_arr['link_reservar_short'])), null, true)?>">
                    </div>
                </div>
                <div id="trc-front">
                    <div id="trc-front-image-box">
                        <img src="<?php echo $ruta_regalo ?>/<?php echo $this->vista_arr['imagen_personalizada']?>">
                    </div>
                    
                    <div id="trc-front-text-area">
                        <span><?php echo $this->translate('tarjeta.imprimible.para')?></span>
                        <span style="font-size: 28px; margin-top:5px;"><?php echo $this->vista_arr['nombre_receptor']?></span>
                    </div>
                    
                </div>
            </div>

        </div>
    </body>